# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uniqueTempKey',
            field=models.CharField(default='myNULL', max_length=200),
        ),
    ]
