# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tool', '0003_auto_20170731_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uniqueTempKey',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
