# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tool', '0005_auto_20170731_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uniqueTempKey',
            field=models.CharField(default='myNull', max_length=200),
        ),
    ]
