# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tool', '0007_post_saledoclink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Event',
        ),
    ]
