# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tool', '0009_auto_20170801_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='saleDocLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
